### PR TITLE
add support for interest groups

### PR DESCRIPTION
**Pull request by fritzmg**
See #5. Needs https://github.com/1up-lab/mailchimp-api-v3/pull/4

### CODE REVIEW

**Comment by fritzmg** [comment]
Ideas for additional features:

* Checkbox whether or not to show interest groups.
* Ability to select which interest group categories to show in the form (sub palette).

**Comment by bytehead** [comment]
https://github.com/1up-lab/mailchimp-api-v3/pull/4 is merged, can you require `oneup/mailchimp-api-v3` in version `2.2.0` as minimum?

**Comment by fritzmg** [comment]
Done :).

When we need it, I'll probably do another PR for those additional features I mentioned.

**Comment by bytehead** [comment]
Perfect, thanks!

**Review by bytehead — APPROVED** [review]

**Pull request merged**
